### ISSUE TITLE
Now is deprecated use now (the template func)

### ISSUE THREAD

**Issue by dch** [forquare/rehyde-x#11]
On running this with hugo 0.26 I get:

```
ERROR 2017/09/13 15:49:42 Page's Now is deprecated and will be removed in Hugo 0.27.
Use now (the template func).
```

This comes from `layouts/partials/sidebar/footer.html` with the `{{ now.Format "2006" }}` line.

`{{ dateFormat "2006" .Date.UTC }}` looks like a suitable replacement, but I have a few other errors blocking getting this updated.

**Comment by forquare** [comment]
Hmm, these messages stopped happening after #1.  Can you tell me a bit more about where you are seeing the message and about your environment?

**Comment by forquare** [comment]
I've built my site with [hugo v0.27.1](https://github.com/gohugoio/hugo/releases/tag/v0.27.1), I'm not getting errors and everything appears to be correct.

**Comment by forquare** [comment]
Closing as no additional information given.
